apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-nm
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: yarn-nm
    {{- include "hadoop.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/component: yarn-nm
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.yarn.nodeManager.pdbMinAvailable }}
