# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-rm
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: yarn-rm
    {{- include "hadoop.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8088
    name: web
  - port: 8032
    name: spark
  selector:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: yarn-rm
    app.kubernetes.io/instance: {{ .Release.Name }}
